### ISSUE TITLE
오류 제보

### ISSUE THREAD

**Issue by jeongjo13** [theseeduser/openNAMU-theseed#1]
안녕하세요, 항상 수고 많으십니다. 이번에 이거 설치하려다가 오류가 나서 제보드립니다.

사용 파이썬 버전: 파이썬애니웨어에서 3.10 버전 사용합니다.

재현 방법: 
1. 일단 Bash 콘솔에 git clone  https://github.com/theseeduser/openNAMU-theseed/ 쳤습니다.
2. 그다음에 Web app setup 가서 Code 부분의 Source code, Working directory 다 수정하고, wsgi 파일도 수정했습니다.(디랙터리는 git clone한 위치에 알맞게 수정했습니다)
3. 그다음에 cd openNAMU-theseed 친 다음에 python3 app.py 치면 아래 오류를 재현할 수 있습니다.

Traceback (most recent call last):
  File "/home/opentestwiki/openNAMU-theseed/app.py", line 5, in <module>
    from route.tool.func import *
  File "/home/opentestwiki/openNAMU-theseed/route/tool/func.py", line 35, in <module>
    with open(os.path.join('data', 'version.json'), 'w', encoding = 'utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/version.json'

**Comment by theseeduser** [comment]
글리치 및 파이썬 3.7에서 코드를 만든 것이라서 타 호스팅에서의 정상 작동은 보증할 수 없습니다. 일단 고쳐보겠습니다.

**Comment by theseeduser** [comment]
해결되었습니다.
